[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git

board_build.filesystem = littlefs
board_build.partitions = default.csv
